### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "6ce4f1bb124b9fdd75cf5851fe8aeb07caccecbd";
          sha256 = "0hks7m8kzlg8l4jv8j16dfy9gdi0lczdp1x8b81vgzxbib9ad3dk";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.14.1";
  selection = 
  {
    base = 
    {
      pname = "base";
      version = "v0.16.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/refs/tags/v0.16.3.tar.gz";
        sha256 = "0g7rrwnd3sb4pcpnvq7hc7dd7rg1gh0axxdhqwjh60dxw81ybycv";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.16.3";
        hash = "sha256:0agy8qgasnz9wc03nssa38b0k76hbm3s8d11v35ppqxr9qiiwcsx";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base_bigstring = 
    {
      pname = "base_bigstring";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/base_bigstring-v0.16.0.tar.gz";
        sha256 = "1hr6m4zjkyxgiskyiwff8sw1rzz4hy83lhbr6r8psmgsl67vzz0r";
      };
      opamInputs = 
      {
        inherit (selection) ppx_jane ocaml int_repr dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base_bigstring/base_bigstring.v0.16.0";
        hash = "sha256:0lr0pjniwmggq6a46ymm80pslbfvvfj08cfcaj1hf64rwimi2i9m";
      };
    };
    base_quickcheck = 
    {
      pname = "base_quickcheck";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/base_quickcheck-v0.16.0.tar.gz";
        sha256 = "0zifdpwjxqlbgcsb6wbq74jfqy8rjfxyd4gqs0ryvki4s9shmy48";
      };
      opamInputs = 
      {
        inherit (selection) splittable_random ppxlib ppx_sexp_value
        ppx_sexp_message ppx_let ppx_fields_conv ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base_quickcheck/base_quickcheck.v0.16.0";
        hash = "sha256:10dj2khzwsm5n5p7jpr3bkgmr619l6plnvdpy2rqbn234x3p0c49";
      };
    };
    bin_prot = 
    {
      pname = "bin_prot";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/bin_prot-v0.16.0.tar.gz";
        sha256 = "1wd2s38hbsza0xc0gfn22h20xmn62kc4kpkspji6n609v24q1piy";
      };
      opamInputs = 
      {
        inherit (selection) ppx_variants_conv ppx_stable_witness
        ppx_sexp_conv ppx_optcomp ppx_fields_conv ppx_custom_printf
        ppx_compare ocaml dune
        base;
        mirage-xen-ocaml = selection.mirage-xen-ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bin_prot/bin_prot.v0.16.0";
        hash = "sha256:11qww3yl5iprx6jwgwd74p4l84nh9x9a0m33h2ssyy6wqmj7a8r3";
      };
    };
    core = 
    {
      pname = "core";
      version = "v0.16.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/core/archive/refs/tags/v0.16.2.tar.gz";
        sha256 = "1zcrbggb63hqfqz1fn8iajzqjab5bimzvnw4bn502npav05kk8wv";
      };
      opamInputs = 
      {
        inherit (selection) variantslib typerep time_now stdio
        splittable_random sexplib ppx_sexp_message ppx_sexp_conv ppx_optcomp
        ppx_jane ppx_inline_test ppx_hash ppx_base ppx_assert ocaml
        jst-config jane-street-headers fieldslib dune bin_prot
        base_quickcheck base_bigstring base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/core/core.v0.16.2";
        hash = "sha256:0hz2lfzxql2mwkam816zc38d5693byf1bfgvmyihb1zy5zk54jid";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.11.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.11.1/dune-3.11.1.tbz";
        sha256 = "0w9zxp2hzi4ndiraclv90jm2nycq82xri7dzyc27dbxdml3j6vw6";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.11.1";
        hash = "sha256:044zsbrg63gjpxfw0bbn0ac8dbg9fnsk3vmi9icy34vbzil97x8k";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.11.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.11.1/dune-3.11.1.tbz";
        sha256 = "0w9zxp2hzi4ndiraclv90jm2nycq82xri7dzyc27dbxdml3j6vw6";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.11.1";
        hash = "sha256:1j5325wx2vj8sx9naafbs2hcpad005qf37skdxdcnrvcmn6bwjf3";
      };
    };
    fieldslib = 
    {
      pname = "fieldslib";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/fieldslib-v0.16.0.tar.gz";
        sha256 = "1wdjb5h8rc7gvsy2sdw3bsixq11cwfzqc3mdz9yp86p7b519bi9c";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fieldslib/fieldslib.v0.16.0";
        hash = "sha256:0fgk3vh3g6k7ryy7wqii24cm97444cnpr0qr5jpn04gl22sh6hk6";
      };
    };
    int_repr = 
    {
      pname = "int_repr";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/int_repr-v0.16.0.tar.gz";
        sha256 = "0xphnqh3cp1qjlbq08ss57q6dhra2g3n090nh7zp3qgy5wk5cbqk";
      };
      opamInputs = 
      {
        inherit (selection) ppx_jane ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/int_repr/int_repr.v0.16.0";
        hash = "sha256:0yrd9nrxm8x1qf30ba16cn3g7w3wlzw2ibhdshcbbknshy145bkl";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jane-street-headers-v0.16.0.tar.gz";
        sha256 = "1sk0scvi657c0jvmdcgi2nmd4aa8qq0vc3q121xli5dlxsgl0vc7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.16.0";
        hash = "sha256:04clgm4x0zbk9v5vs1v068i8ww48q91g1wa2kqxv0i63hawqc8i7";
      };
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/jst-config-v0.16.0.tar.gz";
        sha256 = "0nyr2hyff4s0qq66095p223w9705msdlzmcs17f8r1l2hmnxbsps";
      };
      opamInputs = 
      {
        inherit (selection) ppx_assert ocaml dune-configurator dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.16.0";
        hash = "sha256:1yvn8w6cx3xlx9aiy8zsqg26v59kcdq019lsgz9ybyhn6bj3fjpd";
      };
    };
    myPro = 
    {
      pname = "myPro";
      version = "development";
      src = self.directSrc "myPro";
      opamInputs = 
      {
        inherit (selection) ocaml dune core;
      };
      opamSrc = "myPro.opam";
    };
    num = 
    {
      pname = "num";
      version = "1.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
        sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
      };
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.4";
        hash = "sha256:0sz340iwmhl52zv76lx4r21d1c1s8hpjpcb60c3fwikhfcwx2573";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.14.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.14.1";
        hash = "sha256:16yvyr4nxcpvqp8w7wfhh9rkg2hl4ck3f64fw8kkgx7w2crcp8di";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.14.1.tar.gz";
        sha256 = "0a5h8m8jliw0pf9xwbsnhp534x2qirc1qf3lkmnzpg5ry3k0cq3p";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.14.1";
        hash = "sha256:1kpxp8pd4qw0imw3yxqk2m7fchb12b90nxgmqafha8f77qg6a0jw";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/parsexp-v0.16.0.tar.gz";
        sha256 = "04jywn2q3c4z2xla59qvr0i0bq3zv1p2ghzrp1fai4b1iqn5gqmn";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.16.0";
        hash = "sha256:0rmgxgyd9s1600936l50a1b7xy64yhwk0jjzglzmpvikw2q9dl2x";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_assert-v0.16.0.tar.gz";
        sha256 = "1m9zi1ljdv31afgmi7cfbbgsvl6xhbvg4n69298ivsr730j6xp2p";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.16.0";
        hash = "sha256:06mgc0vf5xxzpavrwfimy4m4hn22pil0nbvabz1q0wbhzslb2n70";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_base-v0.16.0.tar.gz";
        sha256 = "18v9jlykzf9vmf4c817mxl6d3gqy6mx31ksnzai64cix2mimg0v4";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_hash ppx_globalize
        ppx_enumerate ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.16.0";
        hash = "sha256:1g513s531vrrvz4s3cnivrxl5zyl1b848m1v0dpdqd3d795hk7sf";
      };
    };
    ppx_bench = 
    {
      pname = "ppx_bench";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_bench-v0.16.0.tar.gz";
        sha256 = "07bnf528mm7b097jrxc23dnay2nhan18h0gshmb14f6bnhjzq1z3";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_inline_test ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_bench/ppx_bench.v0.16.0";
        hash = "sha256:1ddibn9hkrh53rlqgq4zzl34da590nbn9j4yrvmy4rkklp7iwyhf";
      };
    };
    ppx_bin_prot = 
    {
      pname = "ppx_bin_prot";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_bin_prot-v0.16.0.tar.gz";
        sha256 = "0q9vbjy4473cm1z5jk705wxhnl1cha1nf6aqlf52zwapcdynwj4l";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_here ocaml dune bin_prot base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_bin_prot/ppx_bin_prot.v0.16.0";
        hash = "sha256:1gvhqcj8y650g6khgkjiw8p0i8a65nfswiq05swj38jn47xjc8ch";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_cold-v0.16.0.tar.gz";
        sha256 = "1nm4d8p26mg3yf9vaaw5jspdi4mq2q6bwd5fv13a46jh7dcdnfw0";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.16.0";
        hash = "sha256:1p8gk7scm9rxlxkwkksqnvkpjgva7l9pnn4k6bdpwpdlzjr7qgwa";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_compare-v0.16.0.tar.gz";
        sha256 = "1ai6iz2g8sla5jbqr7n34aw7s5n0cbcqp6w7d95nrpk25s2xvhbs";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.16.0";
        hash = "sha256:0fd2c5xg9l531zbr0d90z8sl51zqpxjbgdv645zzvnvx5nkyca6w";
      };
    };
    ppx_custom_printf = 
    {
      pname = "ppx_custom_printf";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_custom_printf-v0.16.0.tar.gz";
        sha256 = "19m1cj1310c0j0bya3igclyzyg4b20p2161ha2zjlwc1gfdn6q91";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_custom_printf/ppx_custom_printf.v0.16.0";
        hash = "sha256:1kmjrnsmb5hnwishvlz6mra7f7g6xj8b4ckspmv0caicm5i8mf1i";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_disable_unused_warnings = 
    {
      pname = "ppx_disable_unused_warnings";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_disable_unused_warnings-v0.16.0.tar.gz";
        sha256 = "1rwq8b78ykv8c07nv44g3c0k18wba1bdvvw38srlxy7483w8zl9z";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_disable_unused_warnings/ppx_disable_unused_warnings.v0.16.0";
        hash = "sha256:1lrr4pyphrg17mrchw2syv627vnvd83l4vyvfkbhwiqfw8xznlz3";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_enumerate-v0.16.0.tar.gz";
        sha256 = "0lwrxx02shaskn810qba4a7592nd8lkxflgd90ywdi4sdmfn6ci8";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.16.0";
        hash = "sha256:1305lmn66s3ncslsnjswhnc08gs979zh6j62znb78sx99p0af3gk";
      };
    };
    ppx_expect = 
    {
      pname = "ppx_expect";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_expect-v0.16.0.tar.gz";
        sha256 = "0g229sjb2ps1pz3gb21d0xfyg3xja44l91d6ma57axnmw855lyg0";
      };
      opamInputs = 
      {
        inherit (selection) stdio re ppxlib ppx_inline_test ppx_here ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_expect/ppx_expect.v0.16.0";
        hash = "sha256:18saysdmz9mbppp8d0m55gz423j48djyhcay5s73h64i3xsi89jh";
      };
    };
    ppx_fields_conv = 
    {
      pname = "ppx_fields_conv";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_fields_conv-v0.16.0.tar.gz";
        sha256 = "160qqvgq8h6vr9qcm159ddknwcgi9w1yg4d74d31212jifrzm65h";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml fieldslib dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_fields_conv/ppx_fields_conv.v0.16.0";
        hash = "sha256:1bdls3lw4qbig3wxbhdph4dw50dgvqd6gv03qaxc3y9xrjmyg1r6";
      };
    };
    ppx_fixed_literal = 
    {
      pname = "ppx_fixed_literal";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_fixed_literal-v0.16.0.tar.gz";
        sha256 = "0fc392g7hms05iw4s58d0p2bkhh7insqyfp0lswrsgmcz3aa7ld7";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_fixed_literal/ppx_fixed_literal.v0.16.0";
        hash = "sha256:13kmy39ajv334zagf0gpl6xapan2fw27kmsbm05b0lbrfd1mb465";
      };
    };
    ppx_globalize = 
    {
      pname = "ppx_globalize";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_globalize-v0.16.0.tar.gz";
        sha256 = "06s9mfcknbjvsjfgklhizd508zq0vz559lvxn5s2j4b5nysdfs4h";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_globalize/ppx_globalize.v0.16.0";
        hash = "sha256:0s8z4i3cmzcj01amvc1y5q4zd0fy1r46zl20gk8k38by9jvwcy5f";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_hash-v0.16.0.tar.gz";
        sha256 = "1rdn2fzsqjdzx53smn20afxix8c8vav2z03gagyqn9xrnx32a0cv";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.16.0";
        hash = "sha256:0fnqs0xg08r3g9gx9g90gxqxzgncv2383659xdw54dbs604ks6pc";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_here-v0.16.0.tar.gz";
        sha256 = "1w3kjbnp16ypipfracpb0gr7imk4wbnks7j1ngx0dhq04nwri097";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.16.0";
        hash = "sha256:044jv9sjivymm51lrg1p3hnnkp0rhjvi492jqviagarhimwmxlb2";
      };
    };
    ppx_ignore_instrumentation = 
    {
      pname = "ppx_ignore_instrumentation";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_ignore_instrumentation-v0.16.0.tar.gz";
        sha256 = "01ckf16dmvkl9xzdwash610w4wn0k412dsmmb0k8201k47pm0bsj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_ignore_instrumentation/ppx_ignore_instrumentation.v0.16.0";
        hash = "sha256:13v8rmad322b650zwgvs6qfb1jmw2cx5a5lrbpzxy0x5s7371k0h";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.16.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_inline_test/archive/refs/tags/v0.16.1.tar.gz";
        sha256 = "0p99wi0vrk1kn62a0i0qw7gj3bwfw51gclj7j1s6gmr90pjn2kpa";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.16.1";
        hash = "sha256:00w5ndn3cbc3ma4k3c24lk596ds64ykk9jm9phzfwqfjsw97vbr1";
      };
    };
    ppx_jane = 
    {
      pname = "ppx_jane";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_jane-v0.16.0.tar.gz";
        sha256 = "0cy1a6ckl81a7v6x57s08n042iz34zx46zwjns1bx2z3s8fv0lwx";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_variants_conv ppx_typerep_conv
        ppx_tydi ppx_string ppx_stable_witness ppx_stable ppx_sexp_value
        ppx_sexp_message ppx_pipebang ppx_optional ppx_module_timer ppx_log
        ppx_let ppx_inline_test ppx_ignore_instrumentation ppx_here
        ppx_fixed_literal ppx_fields_conv ppx_expect
        ppx_disable_unused_warnings ppx_custom_printf ppx_bin_prot ppx_bench
        ppx_base ppx_assert ocaml dune base_quickcheck;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_jane/ppx_jane.v0.16.0";
        hash = "sha256:0nl20vq579jc0jaadx101dkrn0yrw3vsvgnqqgdx0r22gbfizrl3";
      };
    };
    ppx_let = 
    {
      pname = "ppx_let";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_let-v0.16.0.tar.gz";
        sha256 = "0p76id6wlkjpnypfxmzdx073c2hgf6k0q6vqps3sxw7l00qznjig";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_let/ppx_let.v0.16.0";
        hash = "sha256:0g561g7b5xki84c5yzvy5r2f1m0sbqanhkry6787165mmp9j6984";
      };
    };
    ppx_log = 
    {
      pname = "ppx_log";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_log-v0.16.0.tar.gz";
        sha256 = "1y7sfhfkq7i0b4pk3q1zc4d4m6l1wqrkxlk9s984w7jzgnr2mncl";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ppxlib ppx_sexp_message ppx_sexp_conv
        ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_log/ppx_log.v0.16.0";
        hash = "sha256:1zwhvl6j6im7zy4wv6lb4x7i0hn0xl9hfv6adzxr0900jk0ljr4g";
      };
    };
    ppx_module_timer = 
    {
      pname = "ppx_module_timer";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_module_timer-v0.16.0.tar.gz";
        sha256 = "0x0zyk75n4icca8g60ks6xnfj533gi7jqni4ial7hcywqfz6xvia";
      };
      opamInputs = 
      {
        inherit (selection) time_now stdio ppxlib ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_module_timer/ppx_module_timer.v0.16.0";
        hash = "sha256:00r1xk37k62yckvkf61lgh6dr1587g3qyg9pmzi8wi2dbd97mx6a";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_optcomp-v0.16.0.tar.gz";
        sha256 = "18hbb7nmvrlnsmr6i2l9pyv2mav1jsbjicf6wkydlxak9840kclr";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.16.0";
        hash = "sha256:1yx4r9qhbzm1rx5r9w1490p83z4n1hfjbqg3nnp249g9n83x218w";
      };
    };
    ppx_optional = 
    {
      pname = "ppx_optional";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_optional-v0.16.0.tar.gz";
        sha256 = "1axzphci4md8javp2bf1imh5zr19yj59hlwjnsfs6jywjiklzybh";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optional/ppx_optional.v0.16.0";
        hash = "sha256:0fzxn8bbci4sjc7a6afp1pvz88jq52alq26vcpl2wxq6nbl296li";
      };
    };
    ppx_pipebang = 
    {
      pname = "ppx_pipebang";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_pipebang-v0.16.0.tar.gz";
        sha256 = "0rps3vj6gbq595x3z90qcpngn8k5gc6ys0b4ysq5zifvkkj4gr5r";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_pipebang/ppx_pipebang.v0.16.0";
        hash = "sha256:0xkv8ixkbsghvqavjm616npcachxc0yj72f9i1ccsvnspsr3pa27";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_conv-v0.16.0.tar.gz";
        sha256 = "0390j76ins0hwxn4735ci2j2irgdphfszgq8hi151prvnfivgg21";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.16.0";
        hash = "sha256:14ldpz4hcqbssgcy38h2i2fghw2f2y0m94fb5rjqzsmfy4n2v4yi";
      };
    };
    ppx_sexp_message = 
    {
      pname = "ppx_sexp_message";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_message-v0.16.0.tar.gz";
        sha256 = "0f3xlhq4wcmdkmmqwiv7lvshs6q6fxvihx3vd2s340k7r0fr6a8q";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_message/ppx_sexp_message.v0.16.0";
        hash = "sha256:1w8y1ma0zkl8mw4w76m7x74cwggpk3jjq4lwia13kzmrc66w4mcj";
      };
    };
    ppx_sexp_value = 
    {
      pname = "ppx_sexp_value";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_sexp_value-v0.16.0.tar.gz";
        sha256 = "0sfk65v00p10xj1jjga2zcy6z758s28zmbmwsfvjnn7j9id03m3l";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_value/ppx_sexp_value.v0.16.0";
        hash = "sha256:0kyw1m4zm4nnmjm710pss27wkpbfkg99sdsbhrz7067dlbli83fj";
      };
    };
    ppx_stable = 
    {
      pname = "ppx_stable";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_stable-v0.16.0.tar.gz";
        sha256 = "151h2z1a1b62hl3jjr8y6j88hgm7gvx7mjzpv0i4kjb20rafgf4i";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_stable/ppx_stable.v0.16.0";
        hash = "sha256:1kaicvjacysz47wz8gba2imbd5x9c3m2fd7v98jn2f9ad4l2zzp3";
      };
    };
    ppx_stable_witness = 
    {
      pname = "ppx_stable_witness";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_stable_witness-v0.16.0.tar.gz";
        sha256 = "1vy5g2md1mi9r28rxwlxbcnjwiqrdaa0p56q9f2c6rcx5mhmg62g";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_stable_witness/ppx_stable_witness.v0.16.0";
        hash = "sha256:0f2j5762l3mnwrzghg7rir6ay566bdwcr9yg8rq7y3330fpsnkvw";
      };
    };
    ppx_string = 
    {
      pname = "ppx_string";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_string-v0.16.0.tar.gz";
        sha256 = "0dl32hfiajs2xyapy3b1zsd82risb5pfp4xlzrkbdvm88sa9jnqz";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_string/ppx_string.v0.16.0";
        hash = "sha256:0ns03rz4lrfq0wgg42y14zvgndhm1lzqk852a3l6h71i38nkdygw";
      };
    };
    ppx_tydi = 
    {
      pname = "ppx_tydi";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_tydi-v0.16.0.tar.gz";
        sha256 = "1ijswarkiczz0z9khahmr70np91xn2sskp11jdw5pcsq3wx1aqx3";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_tydi/ppx_tydi.v0.16.0";
        hash = "sha256:0gx8p3w9kr2x39slrg6kvr75wlfv713zs85nba402zg72cgkdr46";
      };
    };
    ppx_typerep_conv = 
    {
      pname = "ppx_typerep_conv";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_typerep_conv-v0.16.0.tar.gz";
        sha256 = "16hd1xwag5qgdrwhbbmdngnm6h9vnflcvh1qgv2vknrhggp6bmgz";
      };
      opamInputs = 
      {
        inherit (selection) typerep ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_typerep_conv/ppx_typerep_conv.v0.16.0";
        hash = "sha256:0cf3y6ipk6hgmr52lhqzs28z9wc2i8vjklzkd87dkild4z3vm6a8";
      };
    };
    ppx_variants_conv = 
    {
      pname = "ppx_variants_conv";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_variants_conv-v0.16.0.tar.gz";
        sha256 = "1r45d34jwdwa3893mvd1as7lh5j68g75nx6h3anynqbnpwsi1ar0";
      };
      opamInputs = 
      {
        inherit (selection) variantslib ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_variants_conv/ppx_variants_conv.v0.16.0";
        hash = "sha256:0ckn6xyic32mhn58hdj5505x30fw5v5pixx9wshix6fwwjmzs4kc";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.31.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.31.0/ppxlib-0.31.0.tbz";
        sha256 = "1n21msr5a6l7j4j1bkzgcqfm4r1vf3lgzjlmg0ns3yjp9rjpc5nj";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.31.0";
        hash = "sha256:0blfx47zi85l729wwm9day7rij78lqyi6ddznkmb9w84f1vhac19";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.11.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz";
        sha256 = "0kwdvzb2wy3rxq3mvmsgc8cdwrzka2viysvrmrrbxxn0h13j9z01";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.11.0";
        hash = "sha256:18048c9lw3g8db1r01diljzvla2pj9bw2fcnvq34gnviwi9rxqjf";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib-v0.16.0.tar.gz";
        sha256 = "0nxc47d9szcxs3vfqfzfxylcpihjza4lwjynbyx18wqmrb8xar75";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.16.0";
        hash = "sha256:19x1c3s6nnj6vk3yil4a4vj8ylzv7v2nk89rpa344jjijq41cvj2";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib0-v0.16.0.tar.gz";
        sha256 = "07bhj2akd6i33h11qin4wns9qnjicf871yzji7vi4i8rd1ja5nw6";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.16.0";
        hash = "sha256:11zmpbm8pj86dmc2fgbz33ngqs1a854dgsayq24hzlvdvif5bgqw";
      };
    };
    splittable_random = 
    {
      pname = "splittable_random";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/splittable_random-v0.16.0.tar.gz";
        sha256 = "1lzn3w92vw8z93r29s5vwps16gl0pyz3f84zwf6c3qq37w31nvz1";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_message ppx_inline_test ppx_bench
        ppx_assert ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/splittable_random/splittable_random.v0.16.0";
        hash = "sha256:1ba9v817315f4pnvm6ssr37k8vibs7s1mg4vafg8n8dd917h9l73";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/stdio-v0.16.0.tar.gz";
        sha256 = "0gm7nci6bi3gfc5q3m8rv4138ip6rhidih3fihvwajk1a1cvgw31";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.16.0";
        hash = "sha256:029985vdqfj1xavwdrhd2kgs8pkfdfkf39bb90fb3ap180fqfw81";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/time_now-v0.16.0.tar.gz";
        sha256 = "18f3dpafs7pj07wnymyhrpp6kzhx1jya5r3ni6xyvap6vsm8982z";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.16.0";
        hash = "sha256:1znd8q9s42jsplz0xrlrvq838q0pia6qp6m5kj48gnsd22c1zfxd";
      };
    };
    typerep = 
    {
      pname = "typerep";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/typerep-v0.16.0.tar.gz";
        sha256 = "0b7pshp8f7k97m690ik0x2gbasj1jfxpfmhsy2n9s8p0c7ppy5g5";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/typerep/typerep.v0.16.0";
        hash = "sha256:0lnvr8avqj50p2hp4y85j0492dv7c2dyp7mf28fvjab8c3nw6h4a";
      };
    };
    variantslib = 
    {
      pname = "variantslib";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/variantslib-v0.16.0.tar.gz";
        sha256 = "0brpknl9ckkn0m2whlkczg9r33z6057sgh1wkk262f0jpk87mbi7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/variantslib/variantslib.v0.16.0";
        hash = "sha256:1xiwyyjzdlsyqc1889q24qzr5f67f8cjv1vq3wydhm2hr73i2ykd";
      };
    };
  };
}

